export function HeroSection() {
  return (
    <div className="text-center space-y-4 mb-12">
      <h1 className="text-5xl md:text-6xl font-bold text-white animate-fade-in">
        News By You and For You
      </h1>
      <p className="text-lg md:text-xl text-zinc-400 max-w-3xl mx-auto animate-fade-in-delay">
        Stop drowning in uninteresting news. With news-use, we provide curated news, generated by Browser Use. Check out what others are interested in <a>here</a>.
      </p>
    </div>
  );
}